[package]
name = "timing"
version = "0.2.1"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2018"
description = "A simple crate for timing stuff"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
